# Generated by Django 6.1 on 2026-08-18 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'cash'), ('online', 'online')], default='cash', max_length=10),
        ),
    ]
